### ISSUE TITLE
Fallback font families should be consistent

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Jean#7]
When specifying fallback font-families with comma separation, we want all those fonts to be of the same type; either serif or sans-serif.  The following CSS:

``` CSS
#JCPP {
    font-family: "Comic Sans MS", cursive, sans-serif;
}
```

mixes sans-serif with serif.  Comic Sans and the generic sans-serif are sans-serif while cursive is serif (meaning a font with decorative flourishes at the end of each stroke).
